version: '3.8'
services:
  app1:
    image: mvp-app
    environment:
      - PORT=8080
    networks:
      - app-network

  app2:
    image: mvp-app
    environment:
      - PORT=8080
    networks:
      - app-network

  app3:
    image: mvp-app
    environment:
      - PORT=8080
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge